import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { RoleTemplate } from '../shared/types.js';
import { logger } from '../shared/logger.js';

/**
 * Integration adapters export an AgentCtx role (plus optional memory notes) into
 * the rules/instructions file another agentic tool reads, so the same persona
 * and project knowledge drive Claude Code, Cursor, and Codex alike.
 *
 *  - `claude-code` → `CLAUDE.md`
 *  - `cursor`      → `.cursorrules`
 *  - `codex`       → `AGENTS.md`
 */

export const SUPPORTED_INTEGRATIONS = ['claude-code', 'codex', 'cursor'] as const;
export type Integration = (typeof SUPPORTED_INTEGRATIONS)[number];

export interface IntegrationInput {
  role: RoleTemplate;
  /** Optional bullets (e.g. relevant memory) appended under "What you should know". */
  notes?: string[];
}

export interface IntegrationAdapter {
  name: Integration;
  /** Rules file written, relative to the project root. */
  rulesFile: string;
  render(input: IntegrationInput): string;
}

function renderRules(label: string, input: IntegrationInput): string {
  const parts = [
    `# ${input.role.name} — ${label} rules (generated by AgentCtx)`,
    '',
    input.role.system_prompt.trim(),
  ];
  if (input.notes && input.notes.length > 0) {
    parts.push('', '## What you should know', input.notes.map((n) => `- ${n}`).join('\n'));
  }
  return parts.join('\n') + '\n';
}

const ADAPTERS: Record<Integration, IntegrationAdapter> = {
  'claude-code': {
    name: 'claude-code',
    rulesFile: 'CLAUDE.md',
    render: (input) => renderRules('Claude Code', input),
  },
  cursor: {
    name: 'cursor',
    rulesFile: '.cursorrules',
    render: (input) => renderRules('Cursor', input),
  },
  codex: {
    name: 'codex',
    rulesFile: 'AGENTS.md',
    render: (input) => renderRules('Codex', input),
  },
};

export function isIntegration(name: string): name is Integration {
  return (SUPPORTED_INTEGRATIONS as readonly string[]).includes(name);
}

export function getIntegration(name: Integration): IntegrationAdapter {
  return ADAPTERS[name];
}

/** Render and write an integration's rules file under `root`. Returns the path. */
export function exportIntegration(name: Integration, input: IntegrationInput, root: string): string {
  const adapter = getIntegration(name);
  const path = join(root, adapter.rulesFile);
  writeFileSync(path, adapter.render(input), 'utf-8');
  logger.debug('exported', name, 'rules to', path);
  return path;
}
